name: Deploy page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          mkdocs gh-deploy --force --clean
